/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c EmailServiceIfProxy -p emailserviceifproxy com.nokia.EmailServiceIf-24799.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef EMAILSERVICEIFPROXY_H_1264589610
#define EMAILSERVICEIFPROXY_H_1264589610

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.nokia.EmailServiceIf
 */
class EmailServiceIfProxy: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName() {
        return "com.nokia.EmailServiceIf";
    }

public:
    EmailServiceIfProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~EmailServiceIfProxy();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> editSendA(const QString &message) {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(message);
        return asyncCallWithArgumentList(QLatin1String("editSendA"), argumentList);
    }

    inline QDBusPendingReply<QString> editSend(const QString &message) {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(message);
        return asyncCallWithArgumentList(QLatin1String("editSend"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void messageSent(const QString &message);
};

namespace com
{
    namespace nokia
    {
        typedef ::EmailServiceIfProxy EmailServiceIf;
    }
}
#endif
