/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c EmailServiceIfProxy -p emailserviceifproxy com.nokia.EmailServiceIf-24799.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "emailserviceifproxy.h"

/*
 * Implementation of interface class EmailServiceIfProxy
 */

EmailServiceIfProxy::EmailServiceIfProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

EmailServiceIfProxy::~EmailServiceIfProxy()
{
}

