/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp duiappletinstancemanagerdbusinterface.xml -a duiappletinstancemanagerdbusadaptor -c DuiAppletInstanceManagerDBusAdaptor -l DuiAppletInstanceManager -i duiappletinstancemanager.h
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "duiappletinstancemanagerdbusadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DuiAppletInstanceManagerDBusAdaptor
 */

DuiAppletInstanceManagerDBusAdaptor::DuiAppletInstanceManagerDBusAdaptor(DuiAppletInstanceManager *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DuiAppletInstanceManagerDBusAdaptor::~DuiAppletInstanceManagerDBusAdaptor()
{
    // destructor
}

void DuiAppletInstanceManagerDBusAdaptor::instantiateAppletFromPackage(const QString &packageName, const QMap<QString, QVariant> &metaData)
{
    // handle method call org.maemo.dui.DuiAppletInstanceManager.instantiateAppletFromPackage
    parent()->instantiateAppletFromPackage(packageName, metaData);
}

