// Add C includes here

#if defined __cplusplus
// Add C++ includes here
#include <QAbstractAnimation>
#include <QAbstractItemModel>
#include <QAbstractProxyModel>
#include <QAbstractTextDocumentLayout>
#include <QAction>
#include <QActionEvent>
#include <QActionGroup>
#include <QAnimationGroup>
#include <QApplication>
#include <QBasicTimer>
#include <QBuffer>
#include <QByteArray>
#include <QClipboard>
#include <QColor>
#include <QContextMenuEvent>
#include <QCoreApplication>
#include <QCryptographicHash>
#include <QDataStream>
#include <QDateTime>
#include <QDebug>
#include <QDir>
#include <QDomDocument>
#include <QEasingCurve>
#include <QEvent>
#include <QEventLoop>
#include <QExplicitlySharedDataPointer>
#include <QFile>
#include <QFileInfo>
#include <QFileSystemWatcher>
#include <QFont>
#include <QFontMetrics>
#include <QFontMetricsF>
#include <QGLContext>
#include <QGLFramebufferObject>
#include <QGLWidget>
#include <QGenericArgument>
#include <QGestureRecognizer>
#include <QGraphicsAnchorLayout>
#include <QGraphicsEffect>
#include <QGraphicsGridLayout>
#include <QGraphicsItem>
#include <QGraphicsLayout>
#include <QGraphicsLayoutItem>
#include <QGraphicsLinearLayout>
#include <QGraphicsScene>
#include <QGraphicsSceneContextMenuEvent>
#include <QGraphicsSceneEvent>
#include <QGraphicsSceneMouseEvent>
#include <QGraphicsSceneResizeEvent>
#include <QGraphicsView>
#include <QGraphicsWidget>
#include <QHash>
#include <QIODevice>
#include <QImage>
#include <QInputContext>
#include <QInputContextFactory>
#include <QInputMethodEvent>
#include <QItemSelection>
#include <QItemSelectionModel>
#include <QLibrary>
#include <QLibraryInfo>
#include <QList>
#include <QLocalServer>
#include <QLocalSocket>
#include <QLocale>
#include <QMap>
#include <QMargins>
#include <QMessageBox>
#include <QMetaObject>
#include <QMetaProperty>
#include <QModelIndex>
#include <QModelIndexList>
#include <QMouseEvent>
#include <QMultiHash>
#include <QMultiMap>
#include <QMutex>
#include <QObject>
#include <QPaintEngine>
#include <QPainter>
#include <QPainterPath>
#include <QPair>
#include <QParallelAnimationGroup>
#include <QPixmap>
#include <QPixmapCache>
#include <QPluginLoader>
#include <QPoint>
#include <QPointF>
#include <QPointer>
#include <QProcess>
#include <QPropertyAnimation>
#include <QQueue>
#include <QRect>
#include <QRectF>
#include <QRegExp>
#include <QRegExpValidator>
#include <QScopedPointer>
#include <QSequentialAnimationGroup>
#include <QSet>
#include <QSettings>
#include <QSharedMemory>
#include <QSharedPointer>
#include <QSignalMapper>
#include <QSize>
#include <QSizeF>
#include <QSizePolicy>
#include <QStandardItemModel>
#include <QString>
#include <QStringList>
#include <QStringListModel>
#include <QStyleOptionGraphicsItem>
#include <QSvgRenderer>
#include <QTapAndHoldGesture>
#include <QTemporaryFile>
#include <QTextBlock>
#include <QTextBlockFormat>
#include <QTextCharFormat>
#include <QTextCodec>
#include <QTextCursor>
#include <QTextDocument>
#include <QTextDocumentFragment>
#include <QTextLayout>
#include <QTextOption>
#include <QTextStream>
#include <QTime>
#include <QTimeLine>
#include <QTimer>
#include <QTranslator>
#include <QUrl>
#include <QValidator>
#include <QVariant>
#include <QVector>
#include <QWidget>
#include <QX11Info>
#include <QtDebug>
#include <QtGlobal>
#include <QtOpenGL>
#include <QtPlugin>

#endif