/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c TextProcessorInterfaceAdaptor -a textprocessorinterfaceadaptor com.nokia.TextProcessorInterface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "textprocessorinterfaceadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TextProcessorInterfaceAdaptor
 */

TextProcessorInterfaceAdaptor::TextProcessorInterfaceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TextProcessorInterfaceAdaptor::~TextProcessorInterfaceAdaptor()
{
    // destructor
}

QString TextProcessorInterfaceAdaptor::reverse(const QString &message)
{
    // handle method call com.nokia.TextProcessorInterface.reverse
    QString out0;
    QMetaObject::invokeMethod(parent(), "reverse", Q_RETURN_ARG(QString, out0), Q_ARG(QString, message));
    return out0;
}

