/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DuiServiceMapperAdaptor -a duiservicemapperadaptor.h:duiservicemapperadaptor.cpp duiservicefw.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "duiservicemapperadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DuiServiceMapperAdaptor
 */

DuiServiceMapperAdaptor::DuiServiceMapperAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DuiServiceMapperAdaptor::~DuiServiceMapperAdaptor()
{
    // destructor
}

QString DuiServiceMapperAdaptor::serviceName(const QString &interfaceName)
{
    // handle method call com.nokia.DuiServiceFwIf.serviceName
    QString out0;
    QMetaObject::invokeMethod(parent(), "serviceName", Q_RETURN_ARG(QString, out0), Q_ARG(QString, interfaceName));
    return out0;
}

QStringList DuiServiceMapperAdaptor::serviceNames(const QString &interfaceName)
{
    // handle method call com.nokia.DuiServiceFwIf.serviceNames
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "serviceNames", Q_RETURN_ARG(QStringList, out0), Q_ARG(QString, interfaceName));
    return out0;
}

QString DuiServiceMapperAdaptor::servicePath(const QString &interfaceName)
{
    // handle method call com.nokia.DuiServiceFwIf.servicePath
    QString out0;
    QMetaObject::invokeMethod(parent(), "servicePath", Q_RETURN_ARG(QString, out0), Q_ARG(QString, interfaceName));
    return out0;
}

QString DuiServiceMapperAdaptor::interfaceName(const QString &serviceName)
{
    // handle method call com.nokia.DuiServiceFwIf.interfaceName
    QString out0;
    QMetaObject::invokeMethod(parent(), "interfaceName", Q_RETURN_ARG(QString, out0), Q_ARG(QString, serviceName));
    return out0;
}
