######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 20 14:00:01 2010
######################################################################

TEMPLATE = app
TARGET =.
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
