/***************************************************************************
**
** Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
** All rights reserved.
** Contact: Nokia Corporation (directui@nokia.com)
**
** This file is part of libdui.
**
** If you have questions regarding the use of this file, please contact
** Nokia at directui@nokia.com.
**
** This library is free software; you can redistribute it and/or
** modify it under the terms of the GNU Lesser General Public
** License version 2.1 as published by the Free Software Foundation
** and appearing in the file LICENSE.LGPL included in the packaging
** of this file.
**
****************************************************************************/

#include <DuiLocale>
#include "ut_duiservicefwgen.h"

#include <DuiApplication>
#include <DuiApplicationWindow>

void Ut_DuiServiceFwGen::init()
{
}

void Ut_DuiServiceFwGen::cleanup()
{
}

DuiApplication *Ut_DuiServiceFwGen::buildApp()
{
    DuiApplication *retVal = 0;

    QChar sep(' ');
    char *argv[MAX_PARAMS];
    int count=1;
    argv[0]=(char *)"ut_duiservicefwgen";

    retVal = new DuiApplication(count, argv);

    return retVal;
}

// this test basically tests that the code generated by the libdui/tools/dui-servicefwgen tool actually compiles
// it's here to catch the case when methods are removed or renamed, since it can seem like nothing is actually using them
void Ut_DuiServiceFwGen::testServiceFwMethods()
{
    app = buildApp();
    delete app;
}

QTEST_APPLESS_MAIN(Ut_DuiServiceFwGen);
