/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c EmailServiceIfAdaptor -a emailserviceifadaptor com.nokia.EmailServiceIf-28323.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef EMAILSERVICEIFADAPTOR_H_1264593365
#define EMAILSERVICEIFADAPTOR_H_1264593365

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.nokia.EmailServiceIf
 */
class EmailServiceIfAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.nokia.EmailServiceIf")
    Q_CLASSINFO("D-Bus Introspection", ""
                "  <interface name=\"com.nokia.EmailServiceIf\">\n"
                "    <method name=\"editSend\">\n"
                "      <arg direction=\"in\" type=\"s\" name=\"message\"/>\n"
                "      <arg direction=\"out\" type=\"s\" name=\"\"/>\n"
                "    </method>\n"
                "    <method name=\"editSendA\">\n"
                "      <arg direction=\"in\" type=\"s\" name=\"message\"/>\n"
                "      <arg direction=\"out\" type=\"s\" name=\"\"/>\n"
                "    </method>\n"
                "    <signal name=\"messageSent\">\n"
                "      <arg direction=\"out\" type=\"s\" name=\"message\"/>\n"
                "    </signal>\n"
                "  </interface>\n"
                "")
public:
    EmailServiceIfAdaptor(QObject *parent);
    virtual ~EmailServiceIfAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString editSendA(const QString &message);
    QString editSend(const QString &message);
Q_SIGNALS: // SIGNALS
    void messageSent(const QString &message);
};

#endif
