/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c EmailServiceIfAdaptor -a emailserviceifadaptor com.nokia.EmailServiceIf.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "emailserviceifadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class EmailServiceIfAdaptor
 */

EmailServiceIfAdaptor::EmailServiceIfAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

EmailServiceIfAdaptor::~EmailServiceIfAdaptor()
{
    // destructor
}

QString EmailServiceIfAdaptor::editSendA(const QString &message)
{
    // handle method call com.nokia.EmailServiceIf.editSendA
    QString out0;
    QMetaObject::invokeMethod(parent(), "editSendA", Q_RETURN_ARG(QString, out0), Q_ARG(QString, message));
    return out0;
}

QString EmailServiceIfAdaptor::editSend(const QString &message)
{
    // handle method call com.nokia.EmailServiceIf.editSend
    QString out0;
    QMetaObject::invokeMethod(parent(), "editSend", Q_RETURN_ARG(QString, out0), Q_ARG(QString, message));
    return out0;
}

