/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c TextProcessorInterfaceAdaptor -a textprocessorinterfaceadaptor com.nokia.TextProcessorInterface-30825.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef TEXTPROCESSORINTERFACEADAPTOR_H_1267695582
#define TEXTPROCESSORINTERFACEADAPTOR_H_1267695582

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.nokia.TextProcessorInterface
 */
class TextProcessorInterfaceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.nokia.TextProcessorInterface")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.nokia.TextProcessorInterface\">\n"
"    <method name=\"reverse\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"message\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    TextProcessorInterfaceAdaptor(QObject *parent);
    virtual ~TextProcessorInterfaceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString reverse(const QString &message);
Q_SIGNALS: // SIGNALS
};

#endif
