/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c TextProcessorIfAdaptor -a textprocessorifadaptor com.nokia.TextProcessorIf.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "textprocessorifadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TextProcessorIfAdaptor
 */

TextProcessorIfAdaptor::TextProcessorIfAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TextProcessorIfAdaptor::~TextProcessorIfAdaptor()
{
    // destructor
}

QString TextProcessorIfAdaptor::reverse(const QString &message)
{
    // handle method call com.nokia.TextProcessorIf.reverse
    QString out0;
    QMetaObject::invokeMethod(parent(), "reverse", Q_RETURN_ARG(QString, out0), Q_ARG(QString, message));
    return out0;
}

