/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c MApplicationIfAdaptor -a mapplicationadaptor.h:mapplicationadaptor.cpp MApplicationIfAdaptor.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "mapplicationifadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <MDebug>

/*
 * Implementation of adaptor class MApplicationIfAdaptor
 */

MApplicationIfAdaptor::MApplicationIfAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MApplicationIfAdaptor::~MApplicationIfAdaptor()
{
    // destructor
}

void MApplicationIfAdaptor::close()
{
    mDebug("MApplicationIfAdaptor") << "MApplicationIfAdaptor::close()";
    // handle method call com.nokia.MApplicationIfAdaptor.close
    QMetaObject::invokeMethod(parent(), "close");
}

void MApplicationIfAdaptor::exit()
{
    mDebug("MApplicationIfAdaptor") << "MApplicationIfAdaptor::exit()";
    // handle method call com.nokia.MApplicationIfAdaptor.exit
    QMetaObject::invokeMethod(parent(), "exit");
}

void MApplicationIfAdaptor::launch()
{
    mDebug("MApplicationIfAdaptor") << "MApplicationIfAdaptor::launch()";
    QMetaObject::invokeMethod(parent(), "launch");
}

void MApplicationIfAdaptor::launch(const QStringList &parameters)
{
    mDebug("MApplicationIfAdaptor") << "MApplicationIfAdaptor::launch(const QStringList&)";
    QMetaObject::invokeMethod(parent(), "launch", Q_ARG(QStringList, parameters));
}
